name: "Nantucket Education Trust"
description: "Nantucket Education Trust"
paginate: 10
markdown: rdiscount
permalink: date
pygments: true
prose:
   siteurl: "http://nantucketeducationtrust.org/"
   base_url: /
   media: "images"