name: "Nantucket Education Trust"
description: "Nantucket Education Trust"
base_url: /
siteurl: 'http://nantucketeducationtrust.org/'
paginate: 10
markdown: rdiscount
permalink: date
pygments: true
prose: 
   media: 'images'